# Generated by Django 3.1.7 on 2021-03-22 14:43

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210320_1928'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.MyUserManager()),
            ],
        ),
    ]
